### ISSUE TITLE
FileNotFoundError: File b'D:/workspace/python/pythonGithubCode/Embedding/InferSent/snli_dir/snli_1.0_train.txt' does not exist

### ISSUE THREAD

**Issue by yongzhuo** [triplemeng/InferSent#1]
Traceback (most recent call last):
['D:/workspace/python/pythonGithubCode/Embedding/InferSent/snli_dir/snli_1.0_train.txt', 'D:/workspace/python/pythonGithubCode/Embedding/InferSent/snli_dir/snli_1.0_dev.txt', 'D:/workspace/python/pythonGithubCode/Embedding/InferSent/snli_dir/snli_1.0_test.txt']
  File "D:/workspace/python/pythonGithubCode/Embedding/InferSent/code/prepare_data.py", line 81, in <module>
    data = initialize(data_dir)
  File "D:/workspace/python/pythonGithubCode/Embedding/InferSent/code/prepare_data.py", line 50, in initialize
    data['train'] = preprocess(snli_train_file)
  File "D:/workspace/python/pythonGithubCode/Embedding/InferSent/code/prepare_data.py", line 33, in preprocess
    data = pd.read_csv(data_file, usecols=['gold_label', 'sentence1', 'sentence2'], sep="\t", header='infer')
  File "D:\software\Anaconda3\envs\py36\lib\site-packages\pandas\io\parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "D:\software\Anaconda3\envs\py36\lib\site-packages\pandas\io\parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\software\Anaconda3\envs\py36\lib\site-packages\pandas\io\parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "D:\software\Anaconda3\envs\py36\lib\site-packages\pandas\io\parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "D:\software\Anaconda3\envs\py36\lib\site-packages\pandas\io\parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas\_libs\parsers.c:4209)
  File "pandas\_libs\parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas\_libs\parsers.c:8873)
FileNotFoundError: File b'D:/workspace/python/pythonGithubCode/Embedding/InferSent/snli_dir/snli_1.0_train.txt' does not exist

**Comment by yongzhuo** [comment]
这里，我实在不能理解，为什么能够用 pd.read_csv读取txt文件





def preprocess(data_file):
    data = pd.read_csv(data_file, usecols=['gold_label', 'sentence1', 'sentence2'], sep="\t", header='infer')
    data['tokenized_sent1'] = data.apply(lambda row:nltk.word_tokenize(str(row['sentence1']).lower()), axis=1)
    data['tokenized_sent2'] = data.apply(lambda row:nltk.word_tokenize(str(row['sentence2']).lower()), axis=1)
    return data

def initialize(data_dir):
    snli_dir = os.path.join(data_dir, "snli_1.0")
    snli_train_file = os.path.join(snli_dir, "snli_1.0_train.txt")
    snli_dev_file = os.path.join(snli_dir, "snli_1.0_dev.txt")
    snli_test_file = os.path.join(snli_dir, "snli_1.0_test.txt")
    files = [snli_train_file, snli_dev_file, snli_test_file]
    print(str(files))
    data = {}
    data['train'] = preprocess(snli_train_file)
    data['dev'] = preprocess(snli_dev_file)
    data['test'] = preprocess(snli_test_file)
    
    return data

**Comment by triplemeng** [comment]
txt 文件只是个名字，只要内容是csv形式的，即有固定分隔符分开不同column的，都可以用read_csv读
Traceback中的错误是文件不存在。你用data.sh文件下载并解压了吗？

**Comment by triplemeng** [comment]
如果没有问题了，我会把这个issue关掉。

**Comment by yongzhuo** [comment]
data.sh运行下不下来，我直接下载网址（https://nlp.stanford.edu/projects/snli/snli_1.0.zip）的文件解压，但是没有csv格式。格式长这样的
neutral	( ( ( A person ) ( on ( a horse ) ) ) ( ( jumps ( over ( a ( broken ( down airplane ) ) ) ) ) . ) )	( ( A person ) ( ( is ( ( training ( his horse ) ) ( for ( a competition ) ) ) ) . ) )	(ROOT (S (NP (NP (DT A) (NN person)) (PP (IN on) (NP (DT a) (NN horse)))) (VP (VBZ jumps) (PP (IN over) (NP (DT a) (JJ broken) (JJ down) (NN airplane)))) (. .)))	(ROOT (S (NP (DT A) (NN person)) (VP (VBZ is) (VP (VBG training) (NP (PRP$ his) (NN horse)) (PP (IN for) (NP (DT a) (NN competition))))) (. .)))	A person on a horse jumps over a broken down airplane.	A person is training his horse for a competition.	3416050480.jpg#4	3416050480.jpg#4r1n	neutral

**Comment by triplemeng** [comment]
是的，这个是csv格式，你可以用preprocess直接处理这个.txt文件
